### ISSUE TITLE
Not enough Details

### ISSUE THREAD

**Issue by RanitManik** [RanitManik/HTML-CSS-Docs#1]
- Flex and Grid page has an important property missing >> `align-self`
- Object-fit page has only one property covered `cover`.Other important properties like `contain` should be included

**Comment by SombitPramanik** [comment]
ok, I will Working on that

**Comment by SombitPramanik** [comment]
Please Mentions in which page this properties will have to be insert, and also please describe the Naming Conversion on the Readme page, for better understanding.
then it is more helpful for me to understand.
